name: Build and Push agrowest

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository-ni klonla
        uses: actions/checkout@v3

      - name: Docker üçün mühit qur
        uses: docker/setup-buildx-action@v2

      - name: GitHub Container Registry üçün login et
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker imajını build et və GitHub Container Registry-ə push et
        run: |
          docker build -t ghcr.io/${{ github.actor }}/fagan:latest .
          docker push ghcr.io/${{ github.actor }}/fagan:latest
